Controllers/CompanyController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VerificationSystem.DB;
using VerificationSystem.Models;
using VerificationSystem.Extensions;
using System.Net;
using System.Data.Entity;

namespace VerificationSystem.Controllers
{
    public class CompanyController : Controller
    {
        private ApplicationDbContext _db;
        public ApplicationDbContext db
        {
            get { return _db ?? HttpContext.GetOwinContext().Get<ApplicationDbContext>(); }
            private set { _db = value; }
        }
        
        // GET: Company
        public ActionResult Index()
        {
            return View(db.Companies.ToList());
        }

        //Get Company Create
        public ActionResult Create()
        {

            return View();

        }

        //Post Company Create
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create(CompanyVM model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                Company company = db.Companies.Create();

                company.Name = model.Name;
                company.Phone1 = model.Phone;
                company.Phone2 = model.Phone2;
                company.Descriptions = model.Description;
                company.Address = model.Address;
                company.RecordBy = User.Identity.GetUserId();
                company.RecordAt = DateTime.Now;
              

                if (model.Disabled) company.DisableDate = DateTime.Now;


                db.Companies.Add(company);
                db.SaveChanges();
                this.AddNotification("Record Saved Succefully", NotificationType.Success);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                this.AddNotification("Something went wrong at this time ERROR:" + ex.Message, NotificationType.Error);
                return View(model);
            }

        }

        //Get Company Edit
        [HttpGet]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound("There is no Company Selected");
            }

            CompanyVM model = new CompanyVM
            {
                Id = company.CompanyId,
                Name = company.Name,
                Description = company.Descriptions,
                Phone = company.Phone1,
                Phone2 = company.Phone2,
                Address = company.Address
                

            };

            if (company.DisableDate !=  null)
            {
                model.DisableDate = company.DisableDate;
                model.Disabled = true;
            }
                

            return View(model);

        }


        //Post Company Edit
        [HttpPost]
        public ActionResult Edit(CompanyVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Company company = db.Companies.Find(model.Id);

                    company.Name = model.Name;
                    company.Phone1 = model.Phone;
                    company.Phone2 = model.Phone2;
                    company.Descriptions = model.Description;
                    company.Address = model.Address;
                    company.UpdateBy = User.Identity.GetUserId().ToString();
                    company.UpdateAt = DateTime.Now;
                  

                    if (model.Disabled )
                        company.DisableDate = model.DisableDate == null ? DateTime.Now : model.DisableDate;
                    else
                        company.DisableDate = null;

                    db.Entry(company).State = EntityState.Modified;
                    db.SaveChanges();


                    this.AddNotification("Record Update Successfully", NotificationType.Success);
                    return RedirectToAction("Index");


                }

                return View(model);

            }
            catch (Exception q)
            {

                this.AddNotification("Something went wrong at this time ERROR:" + q.Message, NotificationType.Error);
                return View(model);
            }


        }

        //Get Details
        public ActionResult Details(long? id, string message)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound("There is no Company is Selected");
            }

            ViewBag.Message = message;
            return View(company);
        }


    }
}

Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using VerificationSystem.Models.Dashboard;
using VerificationSystem.Repositories;

namespace VerificationSystem.Controllers
{
    public class DashboardController : Controller
    {
        private DashboardRepository dashboardRepository;

        public DashboardController()
        {
            dashboardRepository = new DashboardRepository();
        }

        public async Task<ActionResult> Index()
        {
            var vm = new DashboardVM();

            vm.MainCountVM = await dashboardRepository.GetMainCounts();

          

            return View(vm);
        }

    }
}

Controllers/InquiryController.cs
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VerificationSystem.DB;
using VerificationSystem.Models;
using VerificationSystem.Extensions;
using Microsoft.AspNet.Identity;
using System.Drawing.Imaging;
using System.IO;
using System.Drawing;
using System.Net.Http.Headers;
using System.Net;
using Newtonsoft.Json.Linq;
using NinjaNye.SearchExtensions;

using System.Threading.Tasks;

namespace VerificationSystem.Controllers
{
    public class InquiryController : Controller
    {

        private ApplicationDbContext _db;
        public ApplicationDbContext db
        {
            get { return _db ?? HttpContext.GetOwinContext().Get<ApplicationDbContext>(); }
            private set { _db = value; }
        }




        // GET: Inquiry
        public ActionResult Index(int? page, string st, string cm, string ib, string cb, string p, string an, string id, string ac)
        {
            var model = new InquiryIndexVM(db, page, st, cm, ib, cb, p, an, id,ac);
            return View(model);
        }


        [HttpPost]
        public ActionResult  Address(Address model)
        {

            if (ModelState.IsValid)
            {
                Address address;
                if (model.AddressId > 0 )
                {
                    address = db.Addresses.FirstOrDefault(x => x.AddressId == model.AddressId);
                }
                else
                {
                    address = db.Addresses.Create();
                }

                address.Address1 = model.Address1;
                address.Address2 = model.Address2;
                address.Address3 = model.Address3;

                address.City = model.City;

                address.InquiryId = model.InquiryId;
                address.PersonType = model.PersonType;
                address.Province = model.Province;
                address.RecordedBy = User.Identity.GetUserId();
                address.RecordAt = DateTime.Now;
                address.VerificationType = model.VerificationType;
                

                db.Addresses.Add(address);
                if ( model.AddressId > 0 )
                    db.Entry(address).State = System.Data.Entity.EntityState.Modified;
                else
                    db.Entry(address).State = System.Data.Entity.EntityState.Added;

                db.SaveChanges();
                return Json(new { message = $"Address " + (model.AddressId > 0 ? "Updated" : "Saved") + " successfully. ", status = 1, addressId = address.AddressId }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { message = "Field validation error.", status = 0 }, JsonRequestBehavior.AllowGet);
            }
        }


        [HttpGet]
        public ActionResult Create(string id)
        {

            long _id = 0;

            //checking if inquiry id already exist in records, if exists then call different constructor
            if (string.IsNullOrEmpty(id) == false && long.TryParse(id, out _id))
            {
                //Checking if Inquiry Id is correct or not
                var model = new InquiryCreateVM(db, _id);
                return View(model);
            }
            else
            {
                var model = new InquiryCreateVM(db);
                return View(model);

            }
        }
        [HttpPost]

        public async Task<ActionResult> Create(InquiryCreateVM model)
        {
            if (ModelState.IsValid)
            {
                var inquiry = model.Save();
                if (model._status)
                {
                    var ProductName = db.Products.FirstOrDefault(x => x.ProductId == model.ProductId);
               
                    return Json(new { status = 1, inquiryId = inquiry.InquiryId, message = "Inquiry Created susscessfully." });
                }
                else
                    return Json(new { status = 0, message = $"something went wront during the save record please try again later. Message:{model.message}" });
            }

            return Json(new { status = 0, message = "something wrong at this time. Please try again later." });


        }



        [HttpPost]
        public ActionResult CreateResidence(ResidenceCreateVM model)
        {
            if (model == null || model.InquiryId <= 0)
            {
                return Json(new { message = "No id was found.", status = 0 }, JsonRequestBehavior.AllowGet);
            }

            var inquiry = db.Inquiries.FirstOrDefault(x => x.InquiryId == model.InquiryId);


            ResidenceVerification residence;

            if (model.ResidenceVerificationId > 0)
            {
                residence = inquiry.ResidenceVerifications.FirstOrDefault(x => x.ResidenceVerificationId == model.ResidenceVerificationId);

                //checking if person type already exist or not
                if (model.PersonType != model.OldPersonType)
                {
                    if (inquiry.ResidenceVerifications.Any(x => x.PersonType == model.PersonType))
                    {
                        return Json(new { message = "cannot add multiple Residence Verificaiton for same person type.", status = 0 }, JsonRequestBehavior.AllowGet);
                    }
                }
            }
            else
            {
                if (inquiry.ResidenceVerifications.Any(x => x.PersonType == model.PersonType))
                    return Json(new { message = "cannot add multiple Residence Verificaiton for same person type.", status = 0 }, JsonRequestBehavior.AllowGet);

                residence = db.ResidenceVerifications.Create();

            }

            residence.PersonName = model.PersonName;

            residence.PersonType = model.PersonType;

            residence.PersonCNIC = model.PersonCNIC;

            residence.PersonContactNo = model.PersonContactNo;

            residence.ResidenceAddress = model.ResidenceAddress;

            residence.NearestLandMark = model.NearestLandMark;

            residence.InquiryId = inquiry.InquiryId;

            residence.Status = constant.Status.New;


            residence.StatusDate = DateTime.Now;


            var status = db.Statuses.Create();

            status.UserId = User.Identity.GetUserId();

            status.PersonType = residence.PersonType;

            status.VerificationType = constant.VerificationType.Residence;

            status.StatusDate = DateTime.Now;

            if (model.ResidenceVerificationId > 0)
            {

                status.StatusMessage = constant.Status.Edited;

                status.Descriptions = "Recorded after create.....";

                status.VerificationId = model.ResidenceVerificationId.Value;

                inquiry.Statuses.Add(status);

                db.Entry(inquiry).State = System.Data.Entity.EntityState.Modified;
            }
            else
            {
                status.StatusMessage = constant.Status.New;

                status.Descriptions = "Newly created Residence Verification.....";

                inquiry.ResidenceVerifications.Add(residence);

                db.SaveChanges();

                status.VerificationId = residence.ResidenceVerificationId;
                inquiry.Statuses.Add(status);

                db.Entry(inquiry).State = System.Data.Entity.EntityState.Modified;

            }



            if (db.SaveChanges() > 0)
            {
                var residenceList = db.ResidenceVerifications.Where(x => x.InquiryId == model.InquiryId).Select(x => new { x.ResidenceVerificationId, x.InquiryId, x.PersonType, x.PersonName, x.PersonCNIC, x.PersonContactNo, x.ResidenceAddress, x.NearestLandMark }).ToList();
                return Json(new { data = residenceList, status = 1, message = "Verification detail successfully saved." }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { data = "", status = 0, message = "somthing went wrong at this time." }, JsonRequestBehavior.AllowGet);
            }


        }


        [HttpPost]
        public ActionResult CreateWorkOffice(WorkOfficeVM model)
        {
            if (model == null || model.InquiryId <= 0)
            {
                return Json(new { message = "No id was found.", status = 0 }, JsonRequestBehavior.AllowGet);
            }

            var inquiry = db.Inquiries.FirstOrDefault(x => x.InquiryId == model.InquiryId);


            WorkOfficeVerification workoffice;

            if (model.WorkOfficeVerificationId > 0)
            {
                workoffice = inquiry.WorkOfficeVerifications.FirstOrDefault(x => x.WorkOfficeVerificationId == model.WorkOfficeVerificationId);

                //checking if person type already exist or not
                if (model.PersonType != model.OldPersonType)
                {
                    if (inquiry.WorkOfficeVerifications.Any(x => x.PersonType == model.PersonType))
                    {
                        return Json(new { message = "cannot add multiple Work/Office Verification for same person type.", status = 0 }, JsonRequestBehavior.AllowGet);
                    }
                }

            }
            else
            {
                if (inquiry.WorkOfficeVerifications.Any(x => x.PersonType == model.PersonType))
                    return Json(new { message = "cannot add multiple Work/Office Verification for same person type.", status = 0 }, JsonRequestBehavior.AllowGet);

                workoffice = db.WorkOfficeVerifications.Create();

            }



            workoffice.PersonType = model.PersonType;

            workoffice.PersonContactNo = model.PersonContactNo;

            workoffice.PersonDesignation = model.PersonDesignation;

            workoffice.PersonName = model.PersonName;

            workoffice.OfficeName = model.OfficeName;

Views/Shared/Blank.cshtml
@{
    ViewBag.Title = "Blank";
}

Views/Shared/_CustomPager.cshtml
@model VerificationSystem.Models.Pager
@using VerificationSystem.Extensions
@if (Model.EndPage > 1)
{
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="?@Html.GetQueryStringWithParameter("page", ( 1).ToString())">First</a>
            </li>
            <li>
                <a href="?@Html.GetQueryStringWithParameter("page", (Model.CurrentPage - 1).ToString())">Previous</a>
                </li>
        }

        @for (var page = Model.StartPage; page <= Model.EndPage; page++)
        {
            <li class="@(page == Model.CurrentPage ? "active" : "")">
                <a href="?@Html.GetQueryStringWithParameter("page", page.ToString())">@page</a>
            </li>

        }

        @if (Model.CurrentPage < Model.TotalPages)
        {
            <li>
                <a href="?@Html.GetQueryStringWithParameter("page", (Model.CurrentPage + 1).ToString())">Next</a>
            </li>
                <li>
                    <a href="?@Html.GetQueryStringWithParameter("page", (Model.TotalPages).ToString())">Last</a>
                </li>
        }
    </ul>
}

Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>


    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-129194365-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());
        gtag('config', 'UA-129194365-1');
    </script>



    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title - Verification System</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">


    @Styles.Render("~/Content/ui")
    @Styles.Render("~/Content/toastr")

    @Scripts.Render("~/bundles/modernizr")

    @RenderSection("styles", required: false)

</head>


<body class="hold-transition skin-blue sidebar-mini sidebar-collapse">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href='@Url.Action("Index", "Dashboard")' class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>PVS</b></span>
                <!-- logo for regular state and mobile devices -->
                <span style="font-size:13px;"><b>Person Verification System</b></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                @Html.Partial("_LoginPartial")

            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/UI/Dist/img/avatar5.png" class="img-circle" alt="Image">

                    </div>
                    <div class="pull-left info">
                        @if (Request.IsAuthenticated)
                        {

                            <p>
                                @using Microsoft.AspNet.Identity
                                @User.Identity.GetUserName()
                            </p>
                        }
                        else
                        {
                            <p>
                                User
                            </p>
                        }
                       
                    </div>
                </div>

                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header">MAIN NAVIGATION</li>


                    <li>
                        <a href="@Url.Action("Index", "Dashboard")">
                            <i class="fa fa-home"></i> <span>Dashboard</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Inquiry")">
                            <i class="fa fa-check"></i> <span>Inquiries</span>
                        </a>
                    </li>


                    @if (User.IsInRole(constant.Roles.Head) || User.IsInRole(constant.Roles.SuperAdmin))
                    {

                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-plus"></i>
                                <span>Create</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-plus"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="@Url.Action("Create","Inquiry")"><i class="fa fa-plus"></i>Regular</a></li>
                                <li><a href="@Url.Action("Create","Inquiry")"><i class="fa fa-plus"></i>Custom</a></li>
                            </ul>
                        </li>
                        @*<li><a href="@Url.Action("Create","Inquiry")"><i class="fa fa-plus"></i><span>Create Inquiry</span></a></li>*@
                    }



                    @if (User.IsInRole(constant.Roles.SuperAdmin) || User.IsInRole(constant.Roles.Head))
                    {

                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-industry"></i>
                                <span>Company</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="@Url.Action("Index","Company")"><i class="fa fa-list"></i> All Companies</a></li>
                                <li><a href="@Url.Action("Create","Company")"><i class="fa fa-plus"></i> Create New Company</a></li>
                            </ul>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-bank"></i>
                                <span>Customer Branch</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="@Url.Action("Index","CustomerBranch")"><i class="fa fa-list"></i> All Branches</a></li>
                                <li><a href="@Url.Action("Create","CustomerBranch")"><i class="fa fa-plus"></i> Create New Branch</a></li>
                            </ul>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-link"></i>
                                <span>Product</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="@Url.Action("Index","Product")"><i class="fa fa-list"></i> All Products</a></li>
                                <li><a href="@Url.Action("Create","Product")"><i class="fa fa-plus"></i> Create New Product</a></li>
                            </ul>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-user"></i>
                                <span>Account</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="@Url.Action("Index","Account")"><i class="fa fa-users"></i> All Users</a></li>
                                <li><a href="@Url.Action("Register","Account")"><i class="fa fa-plus"></i> Create New User</a></li>
                            </ul>
                        </li>
                    }
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        @*<div class="content-wrapper" style="background-color:#eceff1;">*@
        <div class="content-wrapper">

            <!-- Content Header (Page header) -->
            <section class="content-header"></section>

            <!-- Main content -->
            <section class="content">

                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12 col-lg-12">

                        @Html.Partial("_Notifications")
                        @RenderBody()

                    </div>
                </div>


            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
      

    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")

    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    @Scripts.Render("~/bundles/ui")
    @Scripts.Render("~/bundles/toastr")
    @Scripts.Render("~/bundles/bootbox")


    <style>
        body {
            padding-top: 0px;
            padding-bottom: 0px;
        }
    </style>

    <script>

        /** add active class and stay opened when selected */
        var url = window.location;

        // for sidebar menu entirely but not cover treeview
        $('ul.sidebar-menu a').filter(function () {
            return this.href == url;
        }).parent().addClass('active');

        // for treeview
        $('ul.treeview-menu a').filter(function () {
            return this.href == url;
        }).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');



        $(function () {
            $.fn.serializeObject = function () {

                var form = {};
                $.each($(this).serializeArray(), function (i, field) {
                    form[field.name] = field.value || "";
                });

                return form;
            };
        });
        function setParam(uri, key, val) {
            return uri
                .replace(RegExp("([?&]" + key + "(?=[=&#]|$)[^#&]*|(?=#|$))"), "&" + key + "=" + encodeURIComponent(val))
                .replace(/^([^?&]+)&/, "$1?");
        }
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": false,
            "progressBar": true,
            "positionClass": "toast-bottom-left",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        };

        function ShowLoader(condition, message) {

            if (condition) {
                bootbox.dialog({
                    message: '<div class="text-center"><i class="fa fa-spin fa-spinner fa-2x"></i>  <br/> <span >' + message + '  </span></div>', closeButton: false
                });
            } else {
                bootbox.hideAll();
            }
        }

    </script>

    @RenderSection("scripts", required: false)
</body>
</html>