Controllers/CustomerBranchController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VerificationSystem.DB;
using VerificationSystem.Extensions;
using VerificationSystem.Models;

namespace VerificationSystem.Controllers
{
    public class CustomerBranchController : Controller
    {
        private ApplicationDbContext _db;
        public ApplicationDbContext db
        {
            get { return _db ?? HttpContext.GetOwinContext().Get<ApplicationDbContext>(); }
            private set { _db = value; }
        }

        // GET: Product
        public ActionResult Index()
        {
            return View(db.CustomerBranches.ToList());
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Companies = new SelectList(db.Companies.Where(x => x.DisableDate == null ), "CompanyId", "Name");
            return View();
        }
        [HttpPost]
        public ActionResult Create(CustomerBranchCreateVM model)
        {
            if (ModelState.IsValid)
            {
                var customerBranch = db.CustomerBranches.Create();
                customerBranch.CompanyId = model.CompanyId;
                customerBranch.Name = model.Name;
                customerBranch.Address1 = model.Address;
                customerBranch.Country = model.Country;
                customerBranch.City = model.City;
                customerBranch.Province = model.Province;
                customerBranch.Phone1 = model.Phone1;
                customerBranch.Phone2 = model.Phone2;
                customerBranch.Email = model.Email;

                if (model.Disabled )
                {
                    customerBranch.DisableDate = DateTime.Now;
                }



                db.CustomerBranches.Add(customerBranch);
                db.SaveChanges();
                this.AddNotification("Record Saved Succefully", NotificationType.Success);
                return RedirectToAction("Index" );

            }

            this.AddNotification("There is an error or some field is missing.", NotificationType.Info);

            ViewBag.Companies = new SelectList(db.Companies.Where(x => x.DisableDate == null), "CompanyId", "Name");
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerBranch  customerBranch = db.CustomerBranches.Find(id);
            if (customerBranch == null)
            {
                return HttpNotFound("No product found.");
            }

            CustomerBranchEditVM model = new CustomerBranchEditVM
            {
                CustomerBranchId = customerBranch.CustomerBranchId,
                Name = customerBranch.Name,
                CompanyId = customerBranch.CompanyId, Address = customerBranch.Address1, City = customerBranch.City, Country = customerBranch.Country, Email = customerBranch.Email, Phone1 = customerBranch.Phone1, Phone2 = customerBranch.Phone2, Province = customerBranch.Province
            };
            if (customerBranch.DisableDate != null)
                model.Disabled = true;
           ViewBag.Companies = new SelectList(db.Companies.Where(x => x.DisableDate == null), "CompanyId", "Name", model.CompanyId);
            return View(model);

        }
        [HttpPost]
        public ActionResult Edit(CustomerBranchEditVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    CustomerBranch customerBranch = db.CustomerBranches.Find(model.CustomerBranchId);

                    customerBranch.Name = model.Name;
                    customerBranch.Address1 = model.Address;
                    customerBranch.Country = model.Country;
                    customerBranch.City = model.City;
                    customerBranch.Province = model.Province;
                    customerBranch.Phone1 = model.Phone1;
                    customerBranch.Phone2 = model.Phone2;
                    customerBranch.Email = model.Email;


                    if (model.Disabled)
                        customerBranch.DisableDate = customerBranch.DisableDate == null ? DateTime.Now : customerBranch.DisableDate;
                    else
                        customerBranch.DisableDate = null;
                    

                    db.Entry(customerBranch).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();


                    this.AddNotification("Record Update Successfully", NotificationType.Success);
                    return RedirectToAction("Index");
                }
                ViewBag.Companies = new SelectList(db.Companies.Where(x => x.DisableDate == null), "CompanyId", "Name", model.CompanyId);
                return View(model);
            }
            catch (Exception q)
            {
                this.AddNotification("Something went wrong at this time ERROR:" + q.Message, NotificationType.Error);
                ViewBag.Companies = new SelectList(db.Companies.Where(x => x.DisableDate == null), "CompanyId", "Name", model.CompanyId);
                return View(model);
            }


        }
        public ActionResult Details(long? id, string message)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerBranch  customerBranch = db.CustomerBranches.Find(id);
            if (customerBranch == null)
            {
                return HttpNotFound("There is no Company is Selected");
            }

            ViewBag.Message = message;
            return View(customerBranch);
        }

        
        public ActionResult GetBranchesByCompany(long companyId)
        {
            var branches = db.CustomerBranches.Where(x => x.CompanyId == companyId && x.DisableDate == null).Select(x=> new { x.CustomerBranchId, x.Name }).ToList();
            if (branches.Count > 0)
                return Json(new { branches = branches, status = 1 }, JsonRequestBehavior.AllowGet);
            else
                return Json(new { status = 0 }, JsonRequestBehavior.AllowGet);
        }
    }
}

Controllers/InquiryController.cs
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VerificationSystem.DB;
using VerificationSystem.Models;
using VerificationSystem.Extensions;
using Microsoft.AspNet.Identity;
using System.Drawing.Imaging;
using System.IO;
using System.Drawing;
using System.Net.Http.Headers;
using System.Net;
using Newtonsoft.Json.Linq;
using NinjaNye.SearchExtensions;

using System.Threading.Tasks;

namespace VerificationSystem.Controllers
{
    public class InquiryController : Controller
    {

        private ApplicationDbContext _db;
        public ApplicationDbContext db
        {
            get { return _db ?? HttpContext.GetOwinContext().Get<ApplicationDbContext>(); }
            private set { _db = value; }
        }




        // GET: Inquiry
        public ActionResult Index(int? page, string st, string cm, string ib, string cb, string p, string an, string id, string ac)
        {
            var model = new InquiryIndexVM(db, page, st, cm, ib, cb, p, an, id,ac);
            return View(model);
        }


        [HttpPost]
        public ActionResult  Address(Address model)
        {

            if (ModelState.IsValid)
            {
                Address address;
                if (model.AddressId > 0 )
                {
                    address = db.Addresses.FirstOrDefault(x => x.AddressId == model.AddressId);
                }
                else
                {
                    address = db.Addresses.Create();
                }

                address.Address1 = model.Address1;
                address.Address2 = model.Address2;
                address.Address3 = model.Address3;

                address.City = model.City;

                address.InquiryId = model.InquiryId;
                address.PersonType = model.PersonType;
                address.Province = model.Province;
                address.RecordedBy = User.Identity.GetUserId();
                address.RecordAt = DateTime.Now;
                address.VerificationType = model.VerificationType;
                

                db.Addresses.Add(address);
                if ( model.AddressId > 0 )
                    db.Entry(address).State = System.Data.Entity.EntityState.Modified;
                else
                    db.Entry(address).State = System.Data.Entity.EntityState.Added;

                db.SaveChanges();
                return Json(new { message = $"Address " + (model.AddressId > 0 ? "Updated" : "Saved") + " successfully. ", status = 1, addressId = address.AddressId }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { message = "Field validation error.", status = 0 }, JsonRequestBehavior.AllowGet);
            }
        }


        [HttpGet]
        public ActionResult Create(string id)
        {

            long _id = 0;

            //checking if inquiry id already exist in records, if exists then call different constructor
            if (string.IsNullOrEmpty(id) == false && long.TryParse(id, out _id))
            {
                //Checking if Inquiry Id is correct or not
                var model = new InquiryCreateVM(db, _id);
                return View(model);
            }
            else
            {
                var model = new InquiryCreateVM(db);
                return View(model);

            }
        }
        [HttpPost]

        public async Task<ActionResult> Create(InquiryCreateVM model)
        {
            if (ModelState.IsValid)
            {
                var inquiry = model.Save();
                if (model._status)
                {
                    var ProductName = db.Products.FirstOrDefault(x => x.ProductId == model.ProductId);
               
                    return Json(new { status = 1, inquiryId = inquiry.InquiryId, message = "Inquiry Created susscessfully." });
                }
                else
                    return Json(new { status = 0, message = $"something went wront during the save record please try again later. Message:{model.message}" });
            }

            return Json(new { status = 0, message = "something wrong at this time. Please try again later." });


        }



        [HttpPost]
        public ActionResult CreateResidence(ResidenceCreateVM model)
        {
            if (model == null || model.InquiryId <= 0)
            {
                return Json(new { message = "No id was found.", status = 0 }, JsonRequestBehavior.AllowGet);
            }

            var inquiry = db.Inquiries.FirstOrDefault(x => x.InquiryId == model.InquiryId);


            ResidenceVerification residence;

            if (model.ResidenceVerificationId > 0)
            {
                residence = inquiry.ResidenceVerifications.FirstOrDefault(x => x.ResidenceVerificationId == model.ResidenceVerificationId);

                //checking if person type already exist or not
                if (model.PersonType != model.OldPersonType)
                {
                    if (inquiry.ResidenceVerifications.Any(x => x.PersonType == model.PersonType))
                    {
                        return Json(new { message = "cannot add multiple Residence Verificaiton for same person type.", status = 0 }, JsonRequestBehavior.AllowGet);
                    }
                }
            }
            else
            {
                if (inquiry.ResidenceVerifications.Any(x => x.PersonType == model.PersonType))
                    return Json(new { message = "cannot add multiple Residence Verificaiton for same person type.", status = 0 }, JsonRequestBehavior.AllowGet);

                residence = db.ResidenceVerifications.Create();

            }

            residence.PersonName = model.PersonName;

            residence.PersonType = model.PersonType;

            residence.PersonCNIC = model.PersonCNIC;

            residence.PersonContactNo = model.PersonContactNo;

            residence.ResidenceAddress = model.ResidenceAddress;

            residence.NearestLandMark = model.NearestLandMark;

            residence.InquiryId = inquiry.InquiryId;

            residence.Status = constant.Status.New;


            residence.StatusDate = DateTime.Now;


            var status = db.Statuses.Create();

            status.UserId = User.Identity.GetUserId();

            status.PersonType = residence.PersonType;

            status.VerificationType = constant.VerificationType.Residence;

            status.StatusDate = DateTime.Now;

            if (model.ResidenceVerificationId > 0)
            {

                status.StatusMessage = constant.Status.Edited;

                status.Descriptions = "Recorded after create.....";

                status.VerificationId = model.ResidenceVerificationId.Value;

                inquiry.Statuses.Add(status);

                db.Entry(inquiry).State = System.Data.Entity.EntityState.Modified;
            }
            else
            {
                status.StatusMessage = constant.Status.New;

                status.Descriptions = "Newly created Residence Verification.....";

                inquiry.ResidenceVerifications.Add(residence);

                db.SaveChanges();

                status.VerificationId = residence.ResidenceVerificationId;
                inquiry.Statuses.Add(status);

                db.Entry(inquiry).State = System.Data.Entity.EntityState.Modified;

            }



            if (db.SaveChanges() > 0)
            {
                var residenceList = db.ResidenceVerifications.Where(x => x.InquiryId == model.InquiryId).Select(x => new { x.ResidenceVerificationId, x.InquiryId, x.PersonType, x.PersonName, x.PersonCNIC, x.PersonContactNo, x.ResidenceAddress, x.NearestLandMark }).ToList();
                return Json(new { data = residenceList, status = 1, message = "Verification detail successfully saved." }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { data = "", status = 0, message = "somthing went wrong at this time." }, JsonRequestBehavior.AllowGet);
            }


        }


        [HttpPost]
        public ActionResult CreateWorkOffice(WorkOfficeVM model)
        {
            if (model == null || model.InquiryId <= 0)
            {
                return Json(new { message = "No id was found.", status = 0 }, JsonRequestBehavior.AllowGet);
            }

            var inquiry = db.Inquiries.FirstOrDefault(x => x.InquiryId == model.InquiryId);


            WorkOfficeVerification workoffice;

            if (model.WorkOfficeVerificationId > 0)
            {
                workoffice = inquiry.WorkOfficeVerifications.FirstOrDefault(x => x.WorkOfficeVerificationId == model.WorkOfficeVerificationId);

                //checking if person type already exist or not
                if (model.PersonType != model.OldPersonType)
                {
                    if (inquiry.WorkOfficeVerifications.Any(x => x.PersonType == model.PersonType))
                    {
                        return Json(new { message = "cannot add multiple Work/Office Verification for same person type.", status = 0 }, JsonRequestBehavior.AllowGet);
                    }
                }

            }
            else
            {
                if (inquiry.WorkOfficeVerifications.Any(x => x.PersonType == model.PersonType))
                    return Json(new { message = "cannot add multiple Work/Office Verification for same person type.", status = 0 }, JsonRequestBehavior.AllowGet);

                workoffice = db.WorkOfficeVerifications.Create();

            }



            workoffice.PersonType = model.PersonType;

            workoffice.PersonContactNo = model.PersonContactNo;

            workoffice.PersonDesignation = model.PersonDesignation;

            workoffice.PersonName = model.PersonName;

            workoffice.OfficeName = model.OfficeName;

Views/Inquiry/_CreateInquiry.cshtml
@model VerificationSystem.Models.InquiryCreateVM
@{
    bool renderScript = (bool)ViewData["ScriptSection"];

}


@if (renderScript == false)
{
    using (Html.BeginForm("Create", "Inquiry", FormMethod.Post, new { name = "InquiryForm", id = "InquiryForm" }))
    {

        @Html.AntiForgeryToken();

        @*<div class="row">
                @Html.ValidationSummary(false, "", new { @class = "text=danger" })
            </div>*@
        @Html.HiddenFor(x => x.InquiryId)
        <div class="row">
            @* Inquiry master form *@
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3><strong> Create Inquiry</strong></h3>

                    </div>
                    <div class="box-body">
                        <div class="row " id="row1">
                            <div class="col-md-3">
                                <div class="form-group ">

                                    <div class="col-md-12">
                                        @Html.LabelFor(m => m.BranchId, new { @class = " control-label" })
                                        @Html.DropDownListFor(x => x.BranchId, Model.BranchList, "", new { @class = " form-control chosen-branch  ", data_placeholder = "Select a  Branch" })

                                        @Html.ValidationMessageFor(m => m.BranchId, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group ">
                                    <div class="col-md-12">
                                        @Html.LabelFor(m => m.CompanyId, new { @class = " control-label" })

                                        @Html.DropDownListFor(x => x.CompanyId, Model.CompanyList, "", new { @class = "form-control chosen-company  ", data_placeholder = "Select a Company" })

                                        @Html.ValidationMessageFor(m => m.CompanyId, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="form-group ">
                                    <div class="col-md-12">

                                        @Html.LabelFor(m => m.CustomerBranchId, new { @class = "control-label" })

                                        @Html.DropDownListFor(x => x.CustomerBranchId, Model.CustomerBranchList, "", new { @class = "form-control chosen-customerbranch  ", data_placeholder = "Select a Customer Branch" })

                                        @Html.ValidationMessageFor(m => m.CustomerBranchId, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group ">
                                    <div class="col-md-12">

                                        @Html.LabelFor(m => m.ProductId, new { @class = "control-label" })

                                        @Html.DropDownListFor(x => x.ProductId, Model.ProductList, "", new { @class = "form-control chosen-product  ", data_placeholder = "Select a Product" })

                                        @Html.ValidationMessageFor(m => m.ProductId, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row" id="row2">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        @Html.LabelFor(m => m.AppName, new { @class = " control-label" })


                                        @Html.TextBoxFor(m => m.AppName, new { @class = "form-control" })


                                        @Html.ValidationMessageFor(m => m.AppName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">

                                <div class="form-group">

                                    <div class="col-md-12">
                                        @Html.LabelFor(m => m.AppCNIC, new { @class = " control-label" })
                                        @Html.TextBoxFor(m => m.AppCNIC, new { @class = "form-control" })


                                        @Html.ValidationMessageFor(m => m.AppCNIC, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">

                                    <div class="col-md-12">
                                        @Html.LabelFor(m => m.AppContact, new { @class = " control-label" })
                                        @Html.TextBoxFor(m => m.AppContact, new { @class = "form-control" })


                                        @Html.ValidationMessageFor(m => m.AppContact, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <br />


                                <div class="form-group">
                                    <div class="col-md-12">

                                        <input type="button" class="btn btn-primary btn-block" value="Create New Inquiry" id="CreateInquiry">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }


}
else
{

    <script type="text/javascript">

        //Checking if inquiry id already exists then hide useless divs, and show verifications tabs
        //and assigning values of useful fields that are used to display in front
        @if (@Model.InquiryId > 0)
        {

            @:disableAndHide();
            //Enable Verification Div and display...
            @:$('#div-verification-tabs').removeClass("hidden");

            //Show data of different verifications
            @:$('#salarySlipTable').removeClass('hidden');
            @:$('#tenantTable').removeClass('hidden');
            @:$('#residenceTable').removeClass('hidden');
            @:$('#workOfficeTable').removeClass('hidden');
            @:$('#bankStatementTable').removeClass('hidden');

        }


        $("#CompanyId").change(function () {

            ShowLoader(true, "Please wait");
            $.get('@Url.Action("GetBranchesByCompany", "CustomerBranch")', { companyId: this.value },
            function (data) {
                if (data.status) {
                    fillBranches(data.branches);
                }
                else {
                    this.value = '';
                    $('#CustomerBranchId')
                    .empty();
                }
            });

            $.get('@Url.Action("GetProductsByCompany","Product")', { companyId: this.value },
                function (data) {
                    if (data.status) {
                        fillProducts(data.products);
                    } else {
                        this.value = '';
                        $('#ProductId').empty();
                    }
                });

            ShowLoader(false, "")
        });

        function fillBranches(list) {
            $('#CustomerBranchId')
            .empty();
            var options = '';
            for (var i = 0; i < list.length; i++) {
                options += '<option value="' + list[i].CustomerBranchId + '">' + list[i].Name + '</option>   ';
            }
            $('#CustomerBranchId').append(options);
        }

        function fillProducts(list) {
            $('#ProductId')
            .empty();
            var options = '';
            for (var i = 0; i < list.length; i++) {
                options += '<option value="' + list[i].ProductId + '">' + list[i].Name + '</option>   ';
            }
            $('#ProductId').append(options);
        }

        $('#CreateInquiry').click(function () {
            if ($('#InquiryForm').valid()) {
                ShowLoader(true, "Loading...");
                var dataToPost = $('#InquiryForm').serializeObject();

                $.post('@Url.Action("Create", "Inquiry")', { model: dataToPost },
                    function (data) {
                        if (data.status == 1) {
                            //show message here for alert
                            toastr.success(data.message + "</br> Now add Verification detail in verification type.", "Inquiry Created", { tapToDismiss: false, timeOut: 0, extendedTimeOut: 0 });

                            $('#InquiryId').val(data.inquiryId);
                            disableAndHide();
                            //Enable Verification Div and display...
                            $('#div-verification-tabs').removeClass("hidden");
                            ShowLoader(false, "");
                        }
                        else {
                            toastr.error(data.message, "Inquiry Creation", { tapToDismiss: false, timeOut: 0, extendedTimeOut: 0 });
                            ShowLoader(false, "");
                        }
                    }).fail(function (jqXHR, textStatus,errorThrown) {
                        toastr.error("Network error try again", "Inquiry Creation"+ jqXHR.status, { tapToDismiss: false, timeOut: 0, extendedTimeOut: 0 });
                        
                    });
            } else {

            }
        });

        function disableAndHide() {

            $('#row1').addClass("hidden");
            $('#row2').find('.form-control').attr('disabled', 'disabled');
            $('#CreateInquiry').attr('disabled', 'disabled');

        }


    </script>

}